springdoc:
  api-docs:
    path: /api/documentation/api-docs
  swagger-ui:
    path: /api/documentation/swagger
caching:
  spring:
    conceptsTTL: 86400000 # 1 day
app:
  default:
    languageCode: nb